name       : python-humanize
version    : 4.1.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/h/humanize/humanize-4.1.0.tar.gz : 3a119b242ec872c029d8b7bf8435a61a5798f124b244a08013aec5617302f80e
homepage   : https://github.com/python-humanize/humanize
license    : MIT
component  : programming.python
summary    : Common humanization utilities for Python
description: |
    This modest package contains various common humanization utilities, like turning a number into a fuzzy human readable duration ("3 minutes ago") or into a human readable size or throughput.
builddeps  :
    - python-freezegun      # check
    - python-pytest-cov     # check
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
