name       : python-humanize
version    : 3.2.0
release    : 4
source     :
    - https://pypi.io/packages/source/h/humanize/humanize-3.2.0.tar.gz : ab69004895689951b79f2ae4fdd6b8127ff0c180aff107856d5d98119a33f026
license    : MIT
component  : programming.python
summary    : Common humanization utilities for Python
description: |
    Common humanization utilities for Python
setup      : |
    %python3_setup
install    : |
    %python3_install
