name       : python-humanize
version    : 3.13.1
release    : 5
source     :
    - https://pypi.io/packages/source/h/humanize/humanize-3.13.1.tar.gz : 12f113f2e369dac7f35d3823f49262934f4a22a53a6d3d4c86b736f50db88c7b
homepage   : https://github.com/jmoiron/humanize
license    : MIT
component  : programming.python
summary    : Common humanization utilities for Python
description: |
    This modest package contains various common humanization utilities, like turning a number into a fuzzy human readable duration ("3 minutes ago") or into a human readable size or throughput.
builddeps  :
    - python-freezegun
    - python-pytest-cov
setup      : |
    sed -i '3 i\version: %version%' setup.cfg
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
