name       : python-humanize
version    : 4.0.0
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/h/humanize/humanize-4.0.0.tar.gz : ee1f872fdfc7d2ef4a28d4f80ddde9f96d36955b5d6b0dac4bdeb99502bddb00
homepage   : https://github.com/jmoiron/humanize
license    : MIT
component  : programming.python
summary    : Common humanization utilities for Python
description: |
    This modest package contains various common humanization utilities, like turning a number into a fuzzy human readable duration ("3 minutes ago") or into a human readable size or throughput.
builddeps  :
    - python-freezegun
    - python-pytest-cov
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
