name       : python-humanize
version    : 3.14.0
release    : 6
source     :
    - https://pypi.io/packages/source/h/humanize/humanize-3.14.0.tar.gz : 60dd8c952b1df1ad83f0903844dec50a34ba7a04eea22a6b14204ffb62dbb0a4
homepage   : https://github.com/jmoiron/humanize
license    : MIT
component  : programming.python
summary    : Common humanization utilities for Python
description: |
    This modest package contains various common humanization utilities, like turning a number into a fuzzy human readable duration ("3 minutes ago") or into a human readable size or throughput.
builddeps  :
    - python-freezegun
    - python-pytest-cov
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
