name       : python-humanize
version    : 4.4.0
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/h/humanize/humanize-4.4.0.tar.gz : efb2584565cc86b7ea87a977a15066de34cdedaf341b11c851cfcfd2b964779c
homepage   : https://github.com/python-humanize/humanize
license    : MIT
component  : programming.python
summary    : Common humanization utilities for Python
description: |
    This modest package contains various common humanization utilities, like turning a number into a fuzzy human readable duration ("3 minutes ago") or into a human readable size or throughput.
builddeps  :
    - python-freezegun      # check
    - python-pytest-cov     # check
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
