name       : python-humanize
version    : 0.5.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz : a43f57115831ac7c70de098e6ac46ac13be00d69abbf60bdcac251344785bb19
license    : MIT
component  : programming.python
summary    : Common humanization utilities for Python
description: |
    Common humanization utilities for Python
setup      : |
    %python3_setup
install    : |
    %python3_install
